alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: slack-notifications

    receivers:
      - name: slack-notifications
        slack_configs:
          #- api_url: "enter your slack webhook url here"
            channel: "#general"
            title: "K8s Alert"
            text: "{{ range .Alerts }}{{ .Annotations.description }}{{ end }}"
